//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Json.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace JsonParse {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.CLSCompliant(false)]
public partial class JsonLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		STR_2=10, WS_3=11, INT_6=12, FLOAT_7=13;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"ESCAPED_QUOTE_1", "STR_2", "WS_3", "EXP_5", "INT_6", "DIGIT_4", "FLOAT_7"
	};


	public JsonLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public JsonLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'['", "']'", "'{'", "'}'", "'null'", "'true'", "'false'", "','", 
		"':'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, "STR_2", "WS_3", 
		"INT_6", "FLOAT_7"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Json.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static JsonLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\xF', 'l', '\b', '\x1', '\x4', '\x2', '\t', '\x2', '\x4', 
		'\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', 
		'\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', 
		'\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', 
		'\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\a', '\f', '\x46', 
		'\n', '\f', '\f', '\f', '\xE', '\f', 'I', '\v', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', 
		'\x3', '\xE', '\x6', '\xE', 'S', '\n', '\xE', '\r', '\xE', '\xE', '\xE', 
		'T', '\x3', '\xF', '\x5', '\xF', 'X', '\n', '\xF', '\x3', '\xF', '\x6', 
		'\xF', '[', '\n', '\xF', '\r', '\xF', '\xE', '\xF', '\\', '\x3', '\xF', 
		'\x5', '\xF', '`', '\n', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', 
		'\x5', '\x11', '\x65', '\n', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x5', '\x11', 'k', '\n', '\x11', '\x2', '\x2', 
		'\x12', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', 
		'\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\x2', '\x17', 
		'\f', '\x19', '\r', '\x1B', '\x2', '\x1D', '\xE', '\x1F', '\x2', '!', 
		'\xF', '\x3', '\x2', '\x6', '\x3', '\x2', '$', '$', '\x5', '\x2', '\v', 
		'\f', '\xF', '\xF', '\"', '\"', '\x4', '\x2', 'G', 'G', 'g', 'g', '\x3', 
		'\x2', '\x32', ';', '\x2', 'p', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x3', '#', 
		'\x3', '\x2', '\x2', '\x2', '\x5', '%', '\x3', '\x2', '\x2', '\x2', '\a', 
		'\'', '\x3', '\x2', '\x2', '\x2', '\t', ')', '\x3', '\x2', '\x2', '\x2', 
		'\v', '+', '\x3', '\x2', '\x2', '\x2', '\r', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\xF', '\x35', '\x3', '\x2', '\x2', '\x2', '\x11', ';', '\x3', 
		'\x2', '\x2', '\x2', '\x13', '=', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'?', '\x3', '\x2', '\x2', '\x2', '\x17', '\x42', '\x3', '\x2', '\x2', 
		'\x2', '\x19', 'L', '\x3', '\x2', '\x2', '\x2', '\x1B', 'P', '\x3', '\x2', 
		'\x2', '\x2', '\x1D', 'W', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x61', 
		'\x3', '\x2', '\x2', '\x2', '!', '\x64', '\x3', '\x2', '\x2', '\x2', '#', 
		'$', '\a', ']', '\x2', '\x2', '$', '\x4', '\x3', '\x2', '\x2', '\x2', 
		'%', '&', '\a', '_', '\x2', '\x2', '&', '\x6', '\x3', '\x2', '\x2', '\x2', 
		'\'', '(', '\a', '}', '\x2', '\x2', '(', '\b', '\x3', '\x2', '\x2', '\x2', 
		')', '*', '\a', '\x7F', '\x2', '\x2', '*', '\n', '\x3', '\x2', '\x2', 
		'\x2', '+', ',', '\a', 'p', '\x2', '\x2', ',', '-', '\a', 'w', '\x2', 
		'\x2', '-', '.', '\a', 'n', '\x2', '\x2', '.', '/', '\a', 'n', '\x2', 
		'\x2', '/', '\f', '\x3', '\x2', '\x2', '\x2', '\x30', '\x31', '\a', 'v', 
		'\x2', '\x2', '\x31', '\x32', '\a', 't', '\x2', '\x2', '\x32', '\x33', 
		'\a', 'w', '\x2', '\x2', '\x33', '\x34', '\a', 'g', '\x2', '\x2', '\x34', 
		'\xE', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\a', 'h', '\x2', '\x2', 
		'\x36', '\x37', '\a', '\x63', '\x2', '\x2', '\x37', '\x38', '\a', 'n', 
		'\x2', '\x2', '\x38', '\x39', '\a', 'u', '\x2', '\x2', '\x39', ':', '\a', 
		'g', '\x2', '\x2', ':', '\x10', '\x3', '\x2', '\x2', '\x2', ';', '<', 
		'\a', '.', '\x2', '\x2', '<', '\x12', '\x3', '\x2', '\x2', '\x2', '=', 
		'>', '\a', '<', '\x2', '\x2', '>', '\x14', '\x3', '\x2', '\x2', '\x2', 
		'?', '@', '\a', '^', '\x2', '\x2', '@', '\x41', '\a', '$', '\x2', '\x2', 
		'\x41', '\x16', '\x3', '\x2', '\x2', '\x2', '\x42', 'G', '\a', '$', '\x2', 
		'\x2', '\x43', '\x46', '\x5', '\x15', '\v', '\x2', '\x44', '\x46', '\n', 
		'\x2', '\x2', '\x2', '\x45', '\x43', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\x44', '\x3', '\x2', '\x2', '\x2', '\x46', 'I', '\x3', '\x2', '\x2', 
		'\x2', 'G', '\x45', '\x3', '\x2', '\x2', '\x2', 'G', 'H', '\x3', '\x2', 
		'\x2', '\x2', 'H', 'J', '\x3', '\x2', '\x2', '\x2', 'I', 'G', '\x3', '\x2', 
		'\x2', '\x2', 'J', 'K', '\a', '$', '\x2', '\x2', 'K', '\x18', '\x3', '\x2', 
		'\x2', '\x2', 'L', 'M', '\t', '\x3', '\x2', '\x2', 'M', 'N', '\x3', '\x2', 
		'\x2', '\x2', 'N', 'O', '\b', '\r', '\x2', '\x2', 'O', '\x1A', '\x3', 
		'\x2', '\x2', '\x2', 'P', 'R', '\t', '\x4', '\x2', '\x2', 'Q', 'S', '\x5', 
		'\x1F', '\x10', '\x2', 'R', 'Q', '\x3', '\x2', '\x2', '\x2', 'S', 'T', 
		'\x3', '\x2', '\x2', '\x2', 'T', 'R', '\x3', '\x2', '\x2', '\x2', 'T', 
		'U', '\x3', '\x2', '\x2', '\x2', 'U', '\x1C', '\x3', '\x2', '\x2', '\x2', 
		'V', 'X', '\a', '/', '\x2', '\x2', 'W', 'V', '\x3', '\x2', '\x2', '\x2', 
		'W', 'X', '\x3', '\x2', '\x2', '\x2', 'X', 'Z', '\x3', '\x2', '\x2', '\x2', 
		'Y', '[', '\x5', '\x1F', '\x10', '\x2', 'Z', 'Y', '\x3', '\x2', '\x2', 
		'\x2', '[', '\\', '\x3', '\x2', '\x2', '\x2', '\\', 'Z', '\x3', '\x2', 
		'\x2', '\x2', '\\', ']', '\x3', '\x2', '\x2', '\x2', ']', '_', '\x3', 
		'\x2', '\x2', '\x2', '^', '`', '\x5', '\x1B', '\xE', '\x2', '_', '^', 
		'\x3', '\x2', '\x2', '\x2', '_', '`', '\x3', '\x2', '\x2', '\x2', '`', 
		'\x1E', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\t', '\x5', '\x2', 
		'\x2', '\x62', ' ', '\x3', '\x2', '\x2', '\x2', '\x63', '\x65', '\a', 
		'/', '\x2', '\x2', '\x64', '\x63', '\x3', '\x2', '\x2', '\x2', '\x64', 
		'\x65', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\x3', '\x2', '\x2', 
		'\x2', '\x66', 'g', '\x5', '\x1D', '\xF', '\x2', 'g', 'h', '\a', '\x30', 
		'\x2', '\x2', 'h', 'j', '\x5', '\x1D', '\xF', '\x2', 'i', 'k', '\x5', 
		'\x1B', '\xE', '\x2', 'j', 'i', '\x3', '\x2', '\x2', '\x2', 'j', 'k', 
		'\x3', '\x2', '\x2', '\x2', 'k', '\"', '\x3', '\x2', '\x2', '\x2', '\v', 
		'\x2', '\x45', 'G', 'T', 'W', '\\', '_', '\x64', 'j', '\x3', '\b', '\x2', 
		'\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace JsonParse
