//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from testjson.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ItestjsonListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class testjsonBaseListener : ItestjsonListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="testjsonParser.json"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJson([NotNull] testjsonParser.JsonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="testjsonParser.json"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJson([NotNull] testjsonParser.JsonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="testjsonParser.gen__seplist__L44__pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__seplist__L44__pair([NotNull] testjsonParser.Gen__seplist__L44__pairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="testjsonParser.gen__seplist__L44__pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__seplist__L44__pair([NotNull] testjsonParser.Gen__seplist__L44__pairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="testjsonParser.gen__seplist__L44__json"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__seplist__L44__json([NotNull] testjsonParser.Gen__seplist__L44__jsonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="testjsonParser.gen__seplist__L44__json"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__seplist__L44__json([NotNull] testjsonParser.Gen__seplist__L44__jsonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="testjsonParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPair([NotNull] testjsonParser.PairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="testjsonParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPair([NotNull] testjsonParser.PairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="testjsonParser.str"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStr([NotNull] testjsonParser.StrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="testjsonParser.str"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStr([NotNull] testjsonParser.StrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="testjsonParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] testjsonParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="testjsonParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] testjsonParser.StartContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
